### ISSUE TITLE
Broken in Nightly

### ISSUE THREAD

**Issue by Keith94** [fmileshussey/collapseWiki#1]
In Firefox Nightly 58.0a the "hide" links don't appear.
Browser Console error: `TypeError: current is null  collapse.js:48:9`

**Comment by fmileshussey** [comment]
Hello @Keith94, I greatly appreciate you bringing this to my attn.

Do you mind quickly confirming something for me, on a Wikipedia article that does not have a 'Contents' box i.e. https://en.wikipedia.org/wiki/Place_Saint-Paul do the hide links then appear? Also for the sake of being certain, I presume you are running nightly on Windows?

**Comment by Keith94** [comment]
>do the hide links then appear?

They do. Also yes I'm using Nightly on Windows.

**Comment by fmileshussey** [comment]
Okay thanks for the quick response, I seem to have fixed it. Should be updated now on amo.

**Comment by Keith94** [comment]
Great, thanks for the fix.
